version: '3.8'

services:
  rpg-cards:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    command: ["0.0.0.0", "8080"]
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rpg_data:
    driver: local
